import graphics as gr

window = gr.GraphWin("Gleb and Kuzz project", 400, 400)

face = gr.Rectangle(gr.Point(100, 150), gr.Point(300,250))
telo = gr.Rectangle(gr.Point(100, 250), gr.Point(200,400))

face.setFill('green')
telo.setFill('green')
eye1 = gr.Circle(gr.Point(150, 180), 20)
nos = gr.Circle(gr.Point(270,190), 3)
message = gr.Text(gr.Point(window.getWidth()/2, 30),  'Я прогал всю ночь и я устал')
message.setTextColor('red')
message.setStyle('italic')
message.setSize(20)
konchik = gr.Rectangle(gr.Point(0,350), gr.Point(100,400))
xvost = gr.Rectangle(gr.Point(200,370), gr.Point(400,400))
eye1_center = gr.Circle(gr.Point(150, 180), 8)
eye_center2 = gr.Oval(gr.Point(130, 190), gr.Point(170, 170))
eye1.setFill('yellow')
eye_center2.setFill('red')
eye1_center.setFill('black')
nos.setFill('black')
konchik.setFill('green')
xvost.setFill('green')

window.setBackground('pink')
message.draw(window)
face.draw(window)
eye1.draw(window)
eye_center2.draw(window)
eye1_center.draw(window)
telo.draw(window)
nos.draw(window)
konchik.draw(window)
xvost.draw(window)
window.getMouse()

window.close()