import turtle
a=True
ltl=int(input())
x=0
turtle.shape('turtle')

def fignya(lt):

    turtle.forward(lt)
    turtle.left(90)
    turtle.forward(lt)    
    turtle.right(90)
    turtle.forward(lt) 
    turtle.right(90)    
    turtle.forward(lt) 
    turtle.forward(lt)
    turtle.left(90) 
    turtle.forward(lt) 
    turtle.left(90) 
    turtle.forward(lt) 
    turtle.right(90) 
    turtle.forward(lt) 
 
def fignyaa(lt):

    fignya(lt)
    turtle.left(90)
    fignya(lt)    
    turtle.right(90)
    fignya(lt) 
    turtle.right(90)    
    fignya(lt)
    fignya(lt)
    turtle.left(90) 
    fignya(lt)
    turtle.left(90) 
    fignya(lt) 
    turtle.right(90) 
    fignya(lt)
def fignyaaa(lt):
    fignyaa(lt)
    turtle.left(90)
    fignyaa(lt)    
    turtle.right(90)
    fignyaa(lt) 
    turtle.right(90)    
    fignyaa(lt)
    fignyaa(lt)
    turtle.left(90) 
    fignyaa(lt)
    turtle.left(90) 
    fignyaa(lt) 
    turtle.right(90) 
    fignyaa(lt)
def fignyaaaa(lt):
    fignyaaa(lt)
    turtle.left(90)
    fignyaaa(lt)    
    turtle.right(90)
    fignyaaa(lt) 
    turtle.right(90)    
    fignyaaa(lt)
    fignyaaa(lt)
    turtle.left(90) 
    fignyaaa(lt)
    turtle.left(90) 
    fignyaaa(lt) 
    turtle.right(90) 
    fignyaaa(lt)
def fignyaaaaa(lt):
    fignyaaaa(lt)
    turtle.left(90)
    fignyaaaa(lt)    
    turtle.right(90)
    fignyaaaa(lt) 
    turtle.right(90)    
    fignyaaaa(lt)
    fignyaaaa(lt)
    turtle.left(90) 
    fignyaaaa(lt)
    turtle.left(90) 
    fignyaaaa(lt) 
    turtle.right(90) 
    fignyaaaa(lt)

def fignyaaaaaa(lt):
    fignyaaaaa(lt)
    turtle.left(90)
    fignyaaaaa(lt)    
    turtle.right(90)
    fignyaaaaa(lt) 
    turtle.right(90)    
    fignyaaaaa(lt)
    fignyaaaaa(lt)
    turtle.left(90) 
    fignyaaaaa(lt)
    turtle.left(90) 
    fignyaaaaa(lt) 
    turtle.right(90) 
    fignyaaaaa(lt)
turtle.pen(pencolor="red")
turtle.penup()
turtle.goto(-770,0)
turtle.pendown()
while a:
    fignyaaaaaa(ltl)